version: '3.8'

services:
  migration:
    build: .
    volumes:
      - ./data:/app/data
      - ./migrate_db.py:/app/migrate_db.py
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql://novel_parser:password@postgres:5432/novel_parser}
    command: python migrate_db.py --use-env --sqlite-path data/novels.db
    depends_on:
      - postgres
    networks:
      - novel-parser-network

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-novel_parser}
      POSTGRES_USER: ${POSTGRES_USER:-novel_parser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - novel-parser-network

volumes:
  postgres_data:

networks:
  novel-parser-network:
    driver: bridge
